"""Adiciona coluna entregue na tabela Venda

Revision ID: c75e7fbf692f
Revises: 
Create Date: 2025-06-14 23:22:53.132453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75e7fbf692f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venda_entregue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('data_entrega', sa.DateTime(), nullable=False),
    sa.Column('status_entrega', sa.String(length=50), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('nome_vendedor_entrega', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venda_id')
    )
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrega_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('entrega_status')

    op.drop_table('venda_entregue')
    # ### end Alembic commands ###
